// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	time "time"
	unsafe "unsafe"

	componentconfig "github.com/mYmNeo/lighthouse/pkg/apis/componentconfig"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*HookConfiguration)(nil), (*componentconfig.HookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HookConfiguration_To_componentconfig_HookConfiguration(a.(*HookConfiguration), b.(*componentconfig.HookConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.HookConfiguration)(nil), (*HookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_HookConfiguration_To_v1alpha1_HookConfiguration(a.(*componentconfig.HookConfiguration), b.(*HookConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HookConfigurationItem)(nil), (*componentconfig.HookConfigurationItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HookConfigurationItem_To_componentconfig_HookConfigurationItem(a.(*HookConfigurationItem), b.(*componentconfig.HookConfigurationItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.HookConfigurationItem)(nil), (*HookConfigurationItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_HookConfigurationItem_To_v1alpha1_HookConfigurationItem(a.(*componentconfig.HookConfigurationItem), b.(*HookConfigurationItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HookStage)(nil), (*componentconfig.HookStage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HookStage_To_componentconfig_HookStage(a.(*HookStage), b.(*componentconfig.HookStage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*componentconfig.HookStage)(nil), (*HookStage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_componentconfig_HookStage_To_v1alpha1_HookStage(a.(*componentconfig.HookStage), b.(*HookStage), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_HookConfiguration_To_componentconfig_HookConfiguration(in *HookConfiguration, out *componentconfig.HookConfiguration, s conversion.Scope) error {
	out.Timeout = time.Duration(in.Timeout)
	out.ListenAddress = in.ListenAddress
	out.RemoteEndpoint = in.RemoteEndpoint
	out.WebHooks = *(*componentconfig.HookConfigurationList)(unsafe.Pointer(&in.WebHooks))
	return nil
}

// Convert_v1alpha1_HookConfiguration_To_componentconfig_HookConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_HookConfiguration_To_componentconfig_HookConfiguration(in *HookConfiguration, out *componentconfig.HookConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_HookConfiguration_To_componentconfig_HookConfiguration(in, out, s)
}

func autoConvert_componentconfig_HookConfiguration_To_v1alpha1_HookConfiguration(in *componentconfig.HookConfiguration, out *HookConfiguration, s conversion.Scope) error {
	out.Timeout = time.Duration(in.Timeout)
	out.ListenAddress = in.ListenAddress
	out.RemoteEndpoint = in.RemoteEndpoint
	out.WebHooks = *(*HookConfigurationList)(unsafe.Pointer(&in.WebHooks))
	return nil
}

// Convert_componentconfig_HookConfiguration_To_v1alpha1_HookConfiguration is an autogenerated conversion function.
func Convert_componentconfig_HookConfiguration_To_v1alpha1_HookConfiguration(in *componentconfig.HookConfiguration, out *HookConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_HookConfiguration_To_v1alpha1_HookConfiguration(in, out, s)
}

func autoConvert_v1alpha1_HookConfigurationItem_To_componentconfig_HookConfigurationItem(in *HookConfigurationItem, out *componentconfig.HookConfigurationItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Endpoint = in.Endpoint
	out.FailurePolicy = componentconfig.FailurePolicyType(in.FailurePolicy)
	out.Stages = *(*componentconfig.HookStageList)(unsafe.Pointer(&in.Stages))
	return nil
}

// Convert_v1alpha1_HookConfigurationItem_To_componentconfig_HookConfigurationItem is an autogenerated conversion function.
func Convert_v1alpha1_HookConfigurationItem_To_componentconfig_HookConfigurationItem(in *HookConfigurationItem, out *componentconfig.HookConfigurationItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_HookConfigurationItem_To_componentconfig_HookConfigurationItem(in, out, s)
}

func autoConvert_componentconfig_HookConfigurationItem_To_v1alpha1_HookConfigurationItem(in *componentconfig.HookConfigurationItem, out *HookConfigurationItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Endpoint = in.Endpoint
	out.FailurePolicy = FailurePolicyType(in.FailurePolicy)
	out.Stages = *(*HookStageList)(unsafe.Pointer(&in.Stages))
	return nil
}

// Convert_componentconfig_HookConfigurationItem_To_v1alpha1_HookConfigurationItem is an autogenerated conversion function.
func Convert_componentconfig_HookConfigurationItem_To_v1alpha1_HookConfigurationItem(in *componentconfig.HookConfigurationItem, out *HookConfigurationItem, s conversion.Scope) error {
	return autoConvert_componentconfig_HookConfigurationItem_To_v1alpha1_HookConfigurationItem(in, out, s)
}

func autoConvert_v1alpha1_HookStage_To_componentconfig_HookStage(in *HookStage, out *componentconfig.HookStage, s conversion.Scope) error {
	out.Method = in.Method
	out.URLPattern = in.URLPattern
	out.Type = componentconfig.HookType(in.Type)
	return nil
}

// Convert_v1alpha1_HookStage_To_componentconfig_HookStage is an autogenerated conversion function.
func Convert_v1alpha1_HookStage_To_componentconfig_HookStage(in *HookStage, out *componentconfig.HookStage, s conversion.Scope) error {
	return autoConvert_v1alpha1_HookStage_To_componentconfig_HookStage(in, out, s)
}

func autoConvert_componentconfig_HookStage_To_v1alpha1_HookStage(in *componentconfig.HookStage, out *HookStage, s conversion.Scope) error {
	out.Method = in.Method
	out.URLPattern = in.URLPattern
	out.Type = string(in.Type)
	return nil
}

// Convert_componentconfig_HookStage_To_v1alpha1_HookStage is an autogenerated conversion function.
func Convert_componentconfig_HookStage_To_v1alpha1_HookStage(in *componentconfig.HookStage, out *HookStage, s conversion.Scope) error {
	return autoConvert_componentconfig_HookStage_To_v1alpha1_HookStage(in, out, s)
}
